### ISSUE TITLE
Hook up to Redis

### ISSUE THREAD

**Issue by ahansson89** [mautic/docker-mautic#13]
I read on the forums that Mautic can be hooked up to Redis - let's make this container be able to hook up easily to a Redis container.

Any thoughts?

**Comment by samrose** [comment]
docker-compose is a very easy way to do this on the docker level

**Comment by lvnilesh** [comment]
Here is an incomplete approach. I still do not know how to ask mautic to use mauticredis.

```
version: "3.3"
services:

  mautic:
    image: mautic/mautic
    volumes:
      - /mnt/gluster/mautic.src:/var/www/html
    working_dir: /var/www/html
    environment:
      - MAUTIC_DB_HOST=mauticmariadb
      - MAUTIC_DB_TABLE_PREFIX=mau
      - MAUTIC_RUN_CRON_JOBS=enabled
      - MAUTIC_DB_NAME=mautic
      - MAUTIC_DB_USER=root
      - MAUTIC_DB_PASSWORD=example
    networks:
      - traefik
      - mariadb
    deploy:
      placement:
        constraints: [node.role == worker]
      endpoint_mode: dnsrr
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.backend=domain.com"
        - "traefik.backend.circuitbreaker.expression=NetworkErrorRatio() > 0.5"
        - "traefik.backend.loadbalancer.method=wrr"
        - "traefik.backend.loadbalancer.stickiness=true"
        - "traefik.backend.loadbalancer.stickiness.cookieName=mautic"
        - "traefik.port=80"
        - "traefik.frontend.rule=Host:domain.com"
        - "traefik.frontend.passHostHeader=true"
        - "traefik.docker.network=traefik"

  mauticmariadb:
    image: mariadb:10.3.1
    volumes:
      - /mnt/gluster/mautic.mariadb_vol:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=example
    networks:
      - mariadb
    deploy:
      placement:
        constraints: [node.role == manager]
      replicas: 1
      restart_policy:
        condition: on-failure

  mauticredis:
    image: redis
    networks:
      - mariadb
    deploy:
      placement:
        constraints: [node.role == manager]
      replicas: 1
      restart_policy:
        condition: on-failure


networks:
  traefik:
    external: true
  mariadb:
    external: true

```
