### ISSUE TITLE
How to Get Mautic 3 on a FRESH Install?

### ISSUE THREAD

**Issue by alderson59** [mautic/docker-mautic#182]
Only docker for this discussion. I have tried just about every combination I can think of, as far as docker-compose goes.

What is the best way to get the latest Mautic 3 on a fresh install?

For the below, I am coming in on a fresh install with little experience in wrangling mautic's backend.

I have tried spinning up mautic/mautic:v3, but then I get stuck at the start screen
![image](https://user-images.githubusercontent.com/69715968/102680725-e33ab300-41f5-11eb-897d-f9315318bff8.png)

```
version: "2"
services:
  mautic:
    container_name: mautic3
    restart: unless-stopped
    image: mautic/mautic:v3
    depends_on:
      - db
    ports:
      - "2010:80"
    environment:
      - MAUTIC_DB_HOST=db
      - MAUTIC_DB_USER=mautic
      - MAUTIC_DB_PASSWORD=123
      - MAUTIC_TRUSTED_PROXIES=0.0.0.0/0
    volumes:
      - /srv/mautic3/html:/var/www/html

  db:
    container_name: mautic3_db
    restart: unless-stopped
    image: mariadb:10.4
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_DATABASE=mautic
      - MYSQL_USER=mautic
      - MYSQL_PASSWORD=123
    ports:
      - "2011:3306"
    volumes:
      - /srv/mautic3/mysql:/var/lib/mysql
```
This is the docker compose file for v3 fresh install

* * *

And then I tried installing mautic/mautic:latest (which is v2.16.2) first, and then upgrading via web. Managed to get to v2.16.4 without hiccups.

Side note: mautic/mautic:latest won't work if I tried to access it via host.domain.com (running on nginx proxy manager) despite the configuration below. Only 192.168.x.x:port worked on my local network, which I find odd since trusted proxies are set to all and trusted hosts are left blank. Error 500 pops after step 2, and there were a couple of inconclusive github issues going on here. #141, #142, and #177 (yes, tables didn't get generated if I didn't use the local network to access it)

But I digress. When I reach v2.16.4, I get the option to upgrade to v3, which I did via the web. I don't see how I can do this any other way. Tried console commands (Already checked #149 and tried all the console commands, read the docs), but every attempt is a screw up so far. Already spun and killed dozens of containers at this point in attmepts to figure this out. Hoping someone can clarify.

Anyway, the web upgrade threw this error:

![image](https://user-images.githubusercontent.com/69715968/102680801-bcc94780-41f6-11eb-9191-9be46cb142a2.png)

So I clicked on the link and checked the docs:
![image](https://user-images.githubusercontent.com/69715968/102681041-f3a05d00-41f8-11eb-8aed-97a777b06dab.png)

So it says to check upgrade_log.txt:
![image](https://user-images.githubusercontent.com/69715968/102681049-0b77e100-41f9-11eb-97d6-d98e5586bc9a.png)

Which tells me the same thing as the first image -_-

To replicate, my process was:
1. Get from latest (2.16.2) to 2.16.4 - this works ok
2. docker compose down the :latest and up again with :v3 image in place of :latest (since later versions of PHP is needed)
3. Then it continues to migrate until the screenshot above pops.

Here's the docker compose:
```
version: "2"
services:
  mautic:
    container_name: mautic
    restart: unless-stopped
    image: mautic/mautic:latest
    depends_on:
      - db
    ports:
      - "2000:80"
    environment:
      - MAUTIC_DB_HOST=db
      - MAUTIC_DB_USER=mautic
      - MAUTIC_DB_PASSWORD=abc
      - MAUTIC_TRUSTED_PROXIES=0.0.0.0/0
    volumes:
      - /srv/mautic/html:/var/www/html

  db:
    container_name: mautic_db
    restart: unless-stopped
    image: mariadb:10.4
    environment:
      - MYSQL_ROOT_PASSWORD=abc
      - MYSQL_DATABASE=mautic
      - MYSQL_USER=mautic
      - MYSQL_PASSWORD=abc
    ports:
      - "2001:3306"
    volumes:
      - /srv/mautic/mysql:/var/lib/mysql
```

Does mautic currently allow a fresh install of v3 on docker? If not, what are the steps to get to that?

What am I missing? Why is this so difficult?? Are there many undocumented hidden steps in between?

**Comment by petebytes** [comment]
Try the following https://gist.github.com/petebytes/eb84d374d72fdd0086164426f94c9e23

**Comment by alderson59** [comment]
Thanks. Will test that tonight. Is percona necessary? Won't mariadb work too?

**Comment by petebytes** [comment]
> 
> 
> Thanks. Will test that tonight. Is percona necessary? Won't mariadb work too?

Perhaps try it as is, if it works, them make changes.
mariadb should be fine

**Comment by alderson59** [comment]
So I tried your dc exactly, it works.

When I changed the mount points from volumes to host, perm errors showed up for mysql. And thus the db was not made.
I bypassed this by chowning the dir to 1001:1001 and it works fine.

Then I tried again with mariadb:10.4, with the same parameters as above. Works well.

Here it is in case some future person stumbles upon this issue:

```
version: '2'

services:

  mauticdb:
    image: mariadb:10.4
    container_name: mauticdb
    restart: unless-stopped
    volumes:
      - /srv/mautic/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=yourpassword
    command:
      --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci

  mautic:
    image: mautic/mautic:v3
    container_name: mautic
    restart: unless-stopped
    links:
      - mauticdb:mysql
    depends_on:
      - mauticdb
    ports:
      - "8080:80"
    volumes:
      - /srv/mautic/html:/var/www/html
    environment:
      - MAUTIC_DB_HOST=mauticdb
      - MYSQL_PORT_3306_TCP=3306
      - MAUTIC_DB_USER=root
      - MAUTIC_DB_PASSWORD=yourpassword
      - MAUTIC_DB_NAME=mautic
      - MAUTIC_RUN_CRON_JOBS=true

```

The dc file I started with wasn't too different than this, or so I thought.

Thanks a lot for the help!
