### ISSUE TITLE
Using mautic:v3 image I'm getting the wrong PHP version

### ISSUE THREAD

**Issue by ikus060** [mautic/docker-mautic#218]
With the following docker compose. I'me getting error message in my browser:
```
Fatal error: Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 7.4.0". You are running 7.3.30. in /var/www/html/vendor/composer/platform_check.php on line 24
```

docker-compose.yml:
```
version: "2"

services:
  database:
    image: powertic/percona-docker
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - database:/var/lib/mysql
    restart: always
    networks:
      - mauticnet
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci --sql-mode=""

  mautic:
    container_name: mautic
    image: mautic/mautic:v3-apache
    volumes:
      - mautic_data:/var/www/html
    environment:
      - MAUTIC_DB_HOST=database
      - MAUTIC_DB_USER=root
      - MAUTIC_DB_PASSWORD=mypassword
      - MAUTIC_DB_NAME=mautic4
    restart: always
    networks:
      - mauticnet
    ports:
      - "8880:80"

volumes:
  database:
  mautic_data:
  
networks:
  mauticnet:
```
