### ISSUE TITLE
Basic Docker compose Environment Variable issues

### ISSUE THREAD

**Issue by devilmind81** [mautic/docker-mautic#257]
After done docker-compose up I see these line in the web container:

Check that mariadbd is running and that the socket: '/run/mysqld/mysqld.sock' exists!
mysqladmin: connect to server at '' failed
error: 'Can't connect to server on 'localhost' (99)'
Check that mariadbd is running and that the socket: '/run/mysqld/mysqld.sock' exists!

seems that the environment variables aren't properly set.

Thanks

**Comment by mollux** [comment]
@devilmind81 

could you retry with Mysql instead of MariaDB to rule out it's related to the database (and the supported env vars?

**Comment by devilmind81** [comment]
working only if I add manually the environments value to the docker-compose file:

    environment:
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=mautic_db
      - MYSQL_USER=mautic_db_user
      - MYSQL_PASSWORD=mautic_db_pwd
      - MYSQL_ROOT_PASSWORD=changeme
      - DOCKER_MAUTIC_RUN_MIGRATIONS=false
      - DOCKER_MAUTIC_LOAD_TEST_DATA=false

**Comment by mollux** [comment]
@devilmind81 

that's really strange.
Can you provide following information?
* Docker compose version by executing `docker compose version`
* if you have `jq` installed, the outcome of the command `docker compose config --no-path-resolution --no-normalize --format=json mautic_web | jq  .services.mautic_web.environment`
* if you don't have `jq` installed, the outcome of the command `docker compose config --no-path-resolution --no-normalize --format=json mautic_web`

**Comment by devilmind81** [comment]
Hi, these are the outputs:

Docker Compose version v2.24.5

$ docker compose config --no-path-resolution --no-normalize --format=json mautic_web | jq  .services.mautic_web.environment
{
  "DOCKER_MAUTIC_LOAD_TEST_DATA": "false",
  "DOCKER_MAUTIC_RUN_MIGRATIONS": "false",
  "MAUTIC_DB_DATABASE": "mautic_db",
  "MAUTIC_DB_HOST": "db",
  "MAUTIC_DB_PASSWORD": "mautic_db_pwd",
  "MAUTIC_DB_PORT": "3306",
  "MAUTIC_DB_ROOT_PASSWORD": "changeme",
  "MAUTIC_DB_USER": "mautic_db_user",
  "MAUTIC_MESSENGER_DSN_EMAIL": "doctrine://default",
  "MAUTIC_MESSENGER_DSN_HIT": "doctrine://default"
}

**Comment by mollux** [comment]
@devilmind81 

is this **without** adding the extra lines?
so your `docker-compose.yml` file still looks like this?

```
  mautic_web:
    image: mautic/mautic:5-apache
    links:
      - db:mysql
    ports:
      - 8001:80
    volumes: *mautic-volumes

    environment:
      - DOCKER_MAUTIC_LOAD_TEST_DATA=${DOCKER_MAUTIC_LOAD_TEST_DATA}
      - DOCKER_MAUTIC_RUN_MIGRATIONS=${DOCKER_MAUTIC_RUN_MIGRATIONS}
    env_file:
      - .mautic_env

```
