### ISSUE TITLE
mautic:5.1-fpm cannot be installed - AppTestKernel.php is not found. It is not there

### ISSUE THREAD

**Issue by socialnicheguru** [mautic/docker-mautic#287]
Mautic:5.1-fpm cannot be installed

Warning: require(/var/www/html/vendor/composer/../../docroot/app/AppTestKernel.php): Failed to open stream: No such file or directory in /var/www/html/vendor/composer/autoload_real.php on line 41

Fatal error: Uncaught Error: Failed opening required '/var/www/html/vendor/composer/../../docroot/app/AppTestKernel.php' (include_path='.:/usr/local/lib/php') in /var/www/html/vendor/composer/autoload_real.php:41 Stack trace: #0 /var/www/html/vendor/composer/autoload_real.php(45): {closure}('7f9097acd45f80f...', '/var/www/html/v...') #1 /var/www/html/vendor/autoload.php(25): ComposerAutoloaderInitc287596483174f245407e95fbe560909::getLoader() #2 /var/www/html/docroot/autoload.php(13): require('/var/www/html/v...') #3 /var/www/html/docroot/app/config/bootstrap.php(5): require('/var/www/html/d...') #4 /var/www/html/docroot/index.php(9): require('/var/www/html/d...') #5 {main} thrown in /var/www/html/vendor/composer/autoload_real.php on line 41

when I log into my docker container the file, AppTestKernel.php, is not present on the path or in the system.
root@722386f8bb2c:/var/www/html/docroot/app# ls
AppCache.php   codingstandards		migrations
AppKernel.php  composer.json		phpunit.xml.dist
README.md      config			release_metadata.json
assets	       console-application.php
bundles        middlewares

**Comment by RCheesley** [comment]
I had this happen before when I'd got my root folder set incorrectly in my virtual host - is yours pointing to /docroot per the note in the docs [here](https://docs.mautic.org/en/5.x/getting_started/how_to_install_mautic.html#using-the-recommended-project)?

**Comment by escopecz** [comment]
The `AppTestKernel.php` file isn't even used in production. It's there just to run PHPUNIT tests. What command or action triggers this error?

**Comment by silviupanaite** [comment]
I get the same error on a fresh install using the docker-compose file with migrations enabled.

**Comment by escopecz** [comment]
@silviupanaite by running tests?

**Comment by silviupanaite** [comment]
No did a fresh install using 
```
mautic_web:
    image: mautic/mautic:5-fpm
```
Updated the image to mautic:5.1-fpm and did `docker-compose up` 
relevant options in the env
```
DOCKER_MAUTIC_RUN_MIGRATIONS=true
DOCKER_MAUTIC_LOAD_TEST_DATA=false
```

**Comment by escopecz** [comment]
It will be connected to https://github.com/mautic/mautic/pull/13797 where the AppTestKernel was re-introduced. But the class is clearly there. I can't explain why it's not in your filesystem.

I was testing upgrade from the Apache image from 5.3 to 5.1 while building https://github.com/escopecz/docker-compose-mautic and I had no problems to do so.

**Comment by silviupanaite** [comment]
I retried with `mautic:5-apache` and `mautic:5.1-apache` the result is 
```
mautic_web_1     | [2024-07-23 15:39:15] [notice] Migrating up to Mautic\Migrations\Versionzz20230929183000
mautic_web_1     | [error] Migration Mautic\Migrations\Version20190524124819 failed during Execution. Error: "An exception occurred while executing a query: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'mautic_db.leads' doesn't exist"
mautic_web_1     | 
mautic_web_1     | In ExceptionConverter.php line 49:
mautic_web_1     |                                                                                
mautic_web_1     |   An exception occurred while executing a query: SQLSTATE[42S02]: Base table   
mautic_web_1     |   or view not found: 1146 Table 'mautic_db.leads' doesn't exist                
mautic_web_1     |                                                                                
mautic_web_1     | 
mautic_web_1     | In Exception.php line 28:
mautic_web_1     |                                                                                
mautic_web_1     |   SQLSTATE[42S02]: Base table or view not found: 1146 Table 'mautic_db.leads'  
mautic_web_1     |    doesn't exist                                                               
mautic_web_1     |                                                                                
mautic_web_1     | 
mautic_web_1     | In Statement.php line 130:
mautic_web_1     |                                                                                
mautic_web_1     |   SQLSTATE[42S02]: Base table or view not found: 1146 Table 'mautic_db.leads'  
mautic_web_1     |    doesn't exist                                                               
mautic_web_1     |                                                                                
mautic_web_1     | 
mautic_web_1     | doctrine:migrations:migrate [--write-sql [WRITE-SQL]] [--dry-run] [--query-time] [--allow-no-migration] [--all-or-nothing [ALL-OR-NOTHING]] [--configuration CONFIGURATION] [--em EM] [--conn CONN] [--] [<version>]
mautic_web_1     | 
mautic_web_1     | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 192.168.96.3. Set the 'ServerName' directive globally to suppress this message
mautic_web_1     | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 192.168.96.3. Set the 'ServerName' directive globally to suppress this message
mautic_web_1     | [Tue Jul 23 15:39:16.878818 2024] [mpm_prefork:notice] [pid 18] AH00163: Apache/2.4.59 (Debian) PHP/8.1.29 configured -- resuming normal operations
mautic_web_1     | [Tue Jul 23 15:39:16.878866 2024] [core:notice] [pid 18] AH00094: Command line: 'apache2 -D FOREGROUND'
mautic_web_1     | 127.0.0.1 - - [23/Jul/2024:15:39:20 +0000] "GET / HTTP/1.1" 302 607 "-" "curl/7.88.1"
mautic_web_1     | 127.0.0.1 - - [23/Jul/2024:15:39:26 +0000] "GET / HTTP/1.1" 302 607 "-" "curl/7.88.1"
mautic_web_1     | 127.0.0.1 - - [23/Jul/2024:15:39:31 +0000] "GET / HTTP/1.1" 302 607 "-" "curl/7.88.1"
mautic_web_1     | 127.0.0.1 - - [23/Jul/2024:15:39:36 +0000] "GET / HTTP/1.1" 302 607 "-" "curl/7.88.1"
mautic_web_1     | 127.0.0.1 - - [23/Jul/2024:15:39:41 +0000] "GET / HTTP/1.1" 302 607 "-" "curl/7.88.1"
mautic_web_1     | 127.0.0.1 - - [23/Jul/2024:15:39:46 +0000] "GET / HTTP/1.1" 302 607 "-" "curl/7.88.1"
```

**Comment by escopecz** [comment]
@silviupanaite can you also provide the steps you took along with the output? It's hard to understand the issue without it.

**Comment by silviupanaite** [comment]
```
git clone https://github.com/mautic/docker-mautic.git
cd examples/fpm-nginx
docker-compose up
```
edit the `docker-compose.yaml` and add `5.1-fpm` instead of 5-fpm
```
docker-compose up 
```
I tried your repo, and it works with 5.1  the migration didn't work when I tried

**Comment by escopecz** [comment]
@silviupanaite I cannot replicate following your steps. Can you be more concrete about

> edit the docker-compose.yaml and add 5.1-fpm instead of 5-fpm

Did you replace it in all 3 places?

**Comment by silviupanaite** [comment]
Yes I did replace all the images for worker, cron and web

**Comment by imrodrigoalves** [comment]
Same issue here. While updating the image from `5-fpm`to `5.1-fpm` I get the same error.

```
version: '3.8'

x-mautic-volumes:
  &mautic-volumes
  - ./config:/var/www/html/config:z
  - ./logs:/var/www/html/var/logs:z
  - ./media/files:/var/www/html/media/files:z
  - ./media/images:/var/www/html/media/images:z
  - ./cron:/opt/mautic/cron:z
  - mautic-docroot:/var/www/html/docroot:z

services:
  rabbitmq:
    image: rabbitmq:3
    environment:
      - RABBITMQ_DEFAULT_VHOST=mautic
    volumes: 
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - default
      
  web:
    container_name: mautic_web
    image: mautic/mautic:5-fpm
    restart: unless-stopped
    networks:
      - common-web-network
    volumes: *mautic-volumes
    environment:
      - DOCKER_MAUTIC_ROLE=mautic_web
    env_file:
      - .mautic_env
    healthcheck:
      test: cgi-fcgi -bind -connect 127.0.0.1:9000
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 100
    deploy:
      resources:
        limits:
          memory: 1024M  

  cron:
    image: mautic/mautic:5-fpm
    restart: unless-stopped
    networks:
      - common-web-network
    volumes: *mautic-volumes
    environment:
      - DOCKER_MAUTIC_ROLE=mautic_cron
    env_file:
      - .mautic_env
    depends_on:
      web:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 1536M  

  worker:
    image: mautic/mautic:5-fpm
    restart: unless-stopped
    networks:
      - common-web-network
    volumes: *mautic-volumes
    environment:
      - DOCKER_MAUTIC_ROLE=mautic_worker
    env_file:
      - .mautic_env
    depends_on:
      web:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 1536M   

volumes:
  rabbitmq-data:
  mautic-docroot:
    external: true
  certs:
    external: true
    
networks:
  common-web-network:
    external: true
```
