### ISSUE TITLE
Images not visible in emails

### ISSUE THREAD

**Issue by igisho** [mautic/docker-mautic#291]
mautic version 5.1

my docker compose:

```
version: '3'

x-mautic-volumes:
  &mautic-volumes
  - ./mautic/config:/var/www/html/config:z
  - ./mautic/logs:/var/www/html/var/logs:z
  - ./mautic/media/files:/var/www/html/docroot/media/files:z
  - ./mautic/media/images:/var/www/html/docroot/media/images:z
  - ./cron:/opt/mautic/cron:z
  - mautic-docroot:/var/www/html/docroot:z

services:
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - mautic-docroot:/var/www/html/docroot:z
      - ./certbot/www/:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/letsencrypt/:ro
    depends_on:
      - mautic_web
    ports:
      - 80:80
      - 443:443
    restart: always
    networks:
      - default

  certbot:
    image: certbot/certbot
    volumes:
      - ./credentials.ini:/.secrets/certbot/credentials.ini
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
    networks:
      - default
    entrypoint: /bin/sh -c "pip install certbot-dns-cloudflare && certbot certonly --dns-cloudflare --dns-cloudflare-credentials /.secrets/certbot/credentials.ini -d '*.some.com'"

  mautic_web:
    image: mautic/mautic:5.1-fpm
    volumes: *mautic-volumes
    environment:
      - DOCKER_MAUTIC_LOAD_TEST_DATA=${DOCKER_MAUTIC_LOAD_TEST_DATA}
      - DOCKER_MAUTIC_RUN_MIGRATIONS=${DOCKER_MAUTIC_RUN_MIGRATIONS}
    env_file:
      - .mautic_env
    healthcheck:
      test: cgi-fcgi -bind -connect 127.0.0.1:9000
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 100
    networks:
      - default

  mautic_cron:
    image: mautic/mautic:5.1-fpm
    volumes: *mautic-volumes
    environment:
      - DOCKER_MAUTIC_ROLE=mautic_cron
    env_file:
      - .mautic_env
    depends_on:
      mautic_web:
        condition: service_healthy
    networks:
      - default

  mautic_worker:
    image: mautic/mautic:5.1-fpm
    volumes: *mautic-volumes
    environment:
      - DOCKER_MAUTIC_ROLE=mautic_worker
    env_file:
      - .mautic_env
    depends_on:
      mautic_web:
        condition: service_healthy
    networks:
      - default

volumes:
  mautic-docroot:
  certbot:

networks:
  default:
    name: ${COMPOSE_PROJECT_NAME}-docker
```
    
    
my nginx:

```
server {
    listen 80;

    server_name *.atena.sk;

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name *.atena.sk;

    ssl_certificate /etc/letsencrypt/live/atena.sk/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/atena.sk/privkey.pem;

    root /var/www/html/docroot;

    location / {
        index index.php;
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass mautic_web:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root/$fastcgi_script_name;
    }
}
```

Mautic is running normally, no problem with logs, but images in email are not shown. I can upload and they are uploaded with correct permissions to media/images but in system i can only see empty placeholder thumbnail.
