### ISSUE TITLE
Default docker-compose.yml example dies after short while. 

### ISSUE THREAD

**Issue by chamunks** [mautic/docker-mautic#3]
## Logs

[mautic_mautic_1 log](https://gist.github.com/chamunks/0884bed6df60168f76c8) 
[mautic_mauticdb_1 log](https://gist.github.com/chamunks/e020ed62def56ef15d3d)
## docker-compose.yml

```
mautic:
  image: mautic/mautic
  links:
    - mauticdb:mysql
  ports:
    - 8080:80

mauticdb:
  image: mysql:5.6
  environment:
    MYSQL_ROOT_PASSWORD: example
```
## Error given in web browser.

```
Database connection error (code #1049)
```

**Comment by globsecure** [comment]
@chamunks - This changes:

```
mautic:
  image: mautic/mautic
  links:
    - mauticdb:mysql
  ports:
    - 8080:80
  environment:
    MAUTIC_DB_NAME: mautic
    MAUTIC_DB_USER: root
    MAUTIC_DB_PASSWORD: mautic

mauticdb:
  image: mysql:5.6
  environment:
    MYSQL_ROOT_PASSWORD: mautic
```
