### ISSUE TITLE
Updating image tag to 5.1.1 causes Mautic to throw an internal error

### ISSUE THREAD

**Issue by amks1** [mautic/docker-mautic#304]
### Mautic Series

5.1.x series

### Mautic installed version

5.1.1

### Way of installing

I'm using a Docker image from https://hub.docker.com/r/mautic/mautic

### PHP version

What's in the image

### What browsers are you seeing the problem on?

Chrome

### What happened?

My installation is using docker compose. 
I was using `mautic/mautic:5-apache` which was working well, and just updated the tag to `mautic/mautic:5.1.1-apache`.
The containers start up fine, but on opening the web page it shows:

```
Warning: require(/var/www/html/vendor/composer/../../docroot/app/AppTestKernel.php): Failed to open stream: No such file or directory in /var/www/html/vendor/composer/autoload_real.php on line 41

Fatal error: Uncaught Error: Failed opening required '/var/www/html/vendor/composer/../../docroot/app/AppTestKernel.php' (include_path='.:/usr/local/lib/php') in /var/www/html/vendor/composer/autoload_real.php:41 Stack trace: #0 /var/www/html/vendor/composer/autoload_real.php(45): {closure}('7f9097acd45f80f...', '/var/www/html/v...') mautic/mautic#1 /var/www/html/vendor/autoload.php(25): ComposerAutoloaderInitbccd3ad3db7b670fdd12e172f6f4c035::getLoader() mautic/mautic#2 /var/www/html/docroot/autoload.php(13): require('/var/www/html/v...') mautic/mautic#3 /var/www/html/docroot/app/config/bootstrap.php(5): require('/var/www/html/d...') mautic/mautic#4 /var/www/html/docroot/index.php(9): require('/var/www/html/d...') mautic/mautic#5 {main} thrown in /var/www/html/vendor/composer/autoload_real.php on line 41
```

I also tried updating to `mautic/mautic:5.1.0-apache`, and it gives the same error.

### How can we reproduce this issue?

Step 1: Clone the `mautic/docker-mautic` repo, edit the `docker-compose.yml` file to set the apache version `mautic/mautic:5-apache` and run `docker compose up -d` to install mautic. Check the website to see that it's working fine. 
Step 2: Edit the docker-compose.yml to change the version to `mautic/mautic:5.1.1-apache` in the three containers.
Step 3: Run `docker compose down && docker compose up -d` to rebuild the containers. Go to the website, and it shows the error above.

### Relevant log output

```shell
127.0.0.1 - - [21/Nov/2024:17:58:48 +0000] "GET / HTTP/1.1" 200 1195 "-" "curl/7.88.1"
[Thu Nov 21 17:58:53.492533 2024] [php:warn] [pid 22:tid 22] [client 127.0.0.1:41860] PHP Warning:  require(/var/www/html/vendor/composer/../../docroot/app/AppTestKernel.php): Failed to open stream: No such file or directory in /var/www/html/vendor/composer/autoload_real.php on line 41
[Thu Nov 21 17:58:53.493260 2024] [php:error] [pid 22:tid 22] [client 127.0.0.1:41860] PHP Fatal error:  Uncaught Error: Failed opening required '/var/www/html/vendor/composer/../../docroot/app/AppTestKernel.php' (include_path='.:/usr/local/lib/php') in /var/www/html/vendor/composer/autoload_real.php:41\nStack trace:\n#0 /var/www/html/vendor/composer/autoload_real.php(45): {closure}('7f9097acd45f80f...', '/var/www/html/v...')\n#1 /var/www/html/vendor/autoload.php(25): ComposerAutoloaderInitbccd3ad3db7b670fdd12e172f6f4c035::getLoader()\n#2 /var/www/html/docroot/autoload.php(13): require('/var/www/html/v...')\n#3 /var/www/html/docroot/app/config/bootstrap.php(5): require('/var/www/html/d...')\n#4 /var/www/html/docroot/index.php(9): require('/var/www/html/d...')\n#5 {main}\n  thrown in /var/www/html/vendor/composer/autoload_real.php on line 41
127.0.0.1 - - [21/Nov/2024:17:58:53 +0000] "GET / HTTP/1.1" 200 1195 "-" "curl/7.88.1"
```
```


### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

**Comment by IonutOjicaDE** [comment]
Hey there! I'm helping the new maintainers of this repository. It was neglected for some time but that changes now! Could you please re-test if you are still getting this issue so we could focus our limited time on the issues that are still relevant? If there will be no response we'll close this issue in 1 week. It can always be re-opened later on.

**Comment by cibero42** [comment]
Hello,

This issue is being closed as we didn't get any feedback. Remember that you can always reopen it if you wish to do so!

**Comment by whiteboxsolutions** [comment]
I'd like to re-open this - I've tried `5-fpm`, `5.2.3-fpm`, `5.2.4-fpm`, `5-apache`, `5.2.3-apache`, and `5.2.4-apache` and all of them exhibit the following error:

```
Warning: require(/var/www/html/vendor/composer/../../docroot/app/AppTestKernel.php): Failed to open stream: No such file or directory in /var/www/html/vendor/composer/autoload_real.php on line 41

Fatal error: Uncaught Error: Failed opening required '/var/www/html/vendor/composer/../../docroot/app/AppTestKernel.php' (include_path='.:/usr/local/lib/php') in /var/www/html/vendor/composer/autoload_real.php:41 Stack trace: #0 /var/www/html/vendor/composer/autoload_real.php(45): {closure}('7f9097acd45f80f...', '/var/www/html/v...') #1 /var/www/html/vendor/autoload.php(25): ComposerAutoloaderInit4e4915478812fcf3bb044056d4b6bd1e::getLoader() #2 /var/www/html/docroot/autoload.php(13): require('/var/www/html/v...') #3 /var/www/html/docroot/app/config/bootstrap.php(5): require('/var/www/html/d...') #4 /var/www/html/docroot/index.php(9): require('/var/www/html/d...') #5 {main} thrown in /var/www/html/vendor/composer/autoload_real.php on line 41```


`5.0.4-fpm` works as expected

**Comment by cibero42** [comment]
Hello @whiteboxsolutions ,

Could you please provide your docker compose file?

You're using the fpm version of the image, right? I'd suggest switching to Apache instead, as the current FPM implementation requires mounting the whole html/ directory as persistent, which causes problems when upgrading (see #317).

**Comment by whiteboxsolutions** [comment]
Sure thing. This is the working docker-compose file:

```
services:
  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: mysqladmin --user=$$MYSQL_USER --password=$$MYSQL_PASSWORD ping
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - default

  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - mautic-docroot:/var/www/html/docroot:z
    depends_on:
      - mautic_web
    ports:
      - 8002:80
    networks:
      - default

  mautic_web:
    image: mautic/mautic:5.0.4-fpm
    links:
      - db:mysql
    volumes: *mautic-volumes

    environment:
      - DOCKER_MAUTIC_LOAD_TEST_DATA=${DOCKER_MAUTIC_LOAD_TEST_DATA}
      - DOCKER_MAUTIC_RUN_MIGRATIONS=${DOCKER_MAUTIC_RUN_MIGRATIONS}
    env_file:
      - .mautic_env
    healthcheck:
      test: cgi-fcgi -bind -connect 127.0.0.1:9000
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 100
    depends_on:
      db:
        condition: service_healthy
    networks:
      - default

  mautic_cron:
    image: mautic/mautic:5.0.4-fpm
    links:
      - db:mysql
    volumes: *mautic-volumes
    environment:
      - DOCKER_MAUTIC_ROLE=mautic_cron
    env_file:
      - .mautic_env
    depends_on:
      mautic_web:
        condition: service_healthy
    networks:
      - default

  mautic_worker:
    image: mautic/mautic:5.0.4-fpm
    links:
      - db:mysql
    volumes: *mautic-volumes
    environment:
      - DOCKER_MAUTIC_ROLE=mautic_worker
    env_file:
      - .mautic_env
    depends_on:
      mautic_web:
        condition: service_healthy
    networks:
      - default

volumes:
  mysql-data:
  mautic-docroot:

networks:
  default:
    name: ${COMPOSE_PROJECT_NAME}-docker
```

As per my earlier comment, I tried with fpm AND with Apache. Both exhibited the same issue
