### ISSUE TITLE
Cron seems to be consuming more memory than it should

### ISSUE THREAD

**Issue by O-Mutt** [mautic/docker-mautic#348]
Related data from container:
PHP --ini
```
www-data@826c6bcb03f1:~/html$ php --ini
Configuration File (php.ini) Path: /usr/local/etc/php
Loaded Configuration File:         /usr/local/etc/php/php.ini
Scan for additional .ini files in: /usr/local/etc/php/conf.d
Additional .ini files parsed:      /usr/local/etc/php/conf.d/docker-php-ext-amqp.ini,
/usr/local/etc/php/conf.d/docker-php-ext-bcmath.ini,
/usr/local/etc/php/conf.d/docker-php-ext-exif.ini,
/usr/local/etc/php/conf.d/docker-php-ext-gd.ini,
/usr/local/etc/php/conf.d/docker-php-ext-imap.ini,
/usr/local/etc/php/conf.d/docker-php-ext-intl.ini,
/usr/local/etc/php/conf.d/docker-php-ext-mysqli.ini,
/usr/local/etc/php/conf.d/docker-php-ext-opcache.ini,
/usr/local/etc/php/conf.d/docker-php-ext-pdo_mysql.ini,
/usr/local/etc/php/conf.d/docker-php-ext-sockets.ini,
/usr/local/etc/php/conf.d/docker-php-ext-sodium.ini,
/usr/local/etc/php/conf.d/docker-php-ext-zip.ini

```

grep memory in /usr/local/etc
```
www-data@826c6bcb03f1:~/html$ grep memory /usr/local/etc/php/* -ir
/usr/local/etc/php/php.ini:memory_limit="${PHP_INI_VALUE_MEMORY_LIMIT}"
/usr/local/etc/php/php.ini-development:; Maximum amount of memory a script may consume
/usr/local/etc/php/php.ini-development:; https://php.net/memory-limit
/usr/local/etc/php/php.ini-development:memory_limit = 128M
/usr/local/etc/php/php.ini-development:; If this parameter is set to Off, then memory leaks will not be shown (on
/usr/local/etc/php/php.ini-development:; enabled, registering these variables consumes CPU cycles and memory each time
/usr/local/etc/php/php.ini-development:; to proxy requests or to process the POST data in a memory efficient fashion.
/usr/local/etc/php/php.ini-development:; Enable / Disable collection of memory usage statistics by mysqlnd which can be
/usr/local/etc/php/php.ini-development:mysqlnd.collect_memory_statistics = On
/usr/local/etc/php/php.ini-development:; Default size of the mysqlnd memory pool, which is used by result sets.
/usr/local/etc/php/php.ini-development:; A default size of the shared memory segment
/usr/local/etc/php/php.ini-development:; The OPcache shared memory storage size.
/usr/local/etc/php/php.ini-development:;opcache.memory_consumption=128
/usr/local/etc/php/php.ini-development:; The amount of memory for interned strings in Mbytes.
/usr/local/etc/php/php.ini-development:; The maximum percentage of "wasted" memory until a restart is scheduled.
/usr/local/etc/php/php.ini-development:; memory storage allocation. ("1" means validate once per second, but only
/usr/local/etc/php/php.ini-development:; Preferred Shared Memory back-end. Leave empty and let the system decide.
/usr/local/etc/php/php.ini-development:;opcache.preferred_memory_model=
/usr/local/etc/php/php.ini-development:; Protect the shared memory from unexpected writing during script execution.
/usr/local/etc/php/php.ini-development:;opcache.protect_memory=0
/usr/local/etc/php/php.ini-development:; Mapping base of shared memory segments (for Windows only). All the PHP
/usr/local/etc/php/php.ini-development:; processes have to map shared memory into the same address space. This
/usr/local/etc/php/php.ini-development:; It should improve performance when SHM memory is full, at server restart or
/usr/local/etc/php/php.ini-development:; Enables or disables opcode caching in shared memory.
/usr/local/etc/php/php.ini-development:; reattach to the shared memory (for Windows only). Explicitly enabled file
/usr/local/etc/php/php.ini-development:; delays PHP startup, increases memory usage and degrades performance
/usr/local/etc/php/php.ini-development:; under memory pressure - use with care.
/usr/local/etc/php/php.ini-production:; Maximum amount of memory a script may consume
/usr/local/etc/php/php.ini-production:; https://php.net/memory-limit
/usr/local/etc/php/php.ini-production:memory_limit = 128M
/usr/local/etc/php/php.ini-production:; If this parameter is set to Off, then memory leaks will not be shown (on
/usr/local/etc/php/php.ini-production:; enabled, registering these variables consumes CPU cycles and memory each time
/usr/local/etc/php/php.ini-production:; to proxy requests or to process the POST data in a memory efficient fashion.
/usr/local/etc/php/php.ini-production:; Enable / Disable collection of memory usage statistics by mysqlnd which can be
/usr/local/etc/php/php.ini-production:mysqlnd.collect_memory_statistics = Off
/usr/local/etc/php/php.ini-production:; Default size of the mysqlnd memory pool, which is used by result sets.
/usr/local/etc/php/php.ini-production:; A default size of the shared memory segment
/usr/local/etc/php/php.ini-production:; The OPcache shared memory storage size.
/usr/local/etc/php/php.ini-production:;opcache.memory_consumption=128
/usr/local/etc/php/php.ini-production:; The amount of memory for interned strings in Mbytes.
/usr/local/etc/php/php.ini-production:; The maximum percentage of "wasted" memory until a restart is scheduled.
/usr/local/etc/php/php.ini-production:; memory storage allocation. ("1" means validate once per second, but only
/usr/local/etc/php/php.ini-production:; Preferred Shared Memory back-end. Leave empty and let the system decide.
/usr/local/etc/php/php.ini-production:;opcache.preferred_memory_model=
/usr/local/etc/php/php.ini-production:; Protect the shared memory from unexpected writing during script execution.
/usr/local/etc/php/php.ini-production:;opcache.protect_memory=0
/usr/local/etc/php/php.ini-production:; Mapping base of shared memory segments (for Windows only). All the PHP
/usr/local/etc/php/php.ini-production:; processes have to map shared memory into the same address space. This
/usr/local/etc/php/php.ini-production:; It should improve performance when SHM memory is full, at server restart or
/usr/local/etc/php/php.ini-production:; Enables or disables opcode caching in shared memory.
/usr/local/etc/php/php.ini-production:; reattach to the shared memory (for Windows only). Explicitly enabled file
/usr/local/etc/php/php.ini-production:; delays PHP startup, increases memory usage and degrades performance
/usr/local/etc/php/php.ini-production:; under memory pressure - use with care.
```

echo out memory limit
```
www-data@826c6bcb03f1:~/html$ echo $PHP_INI_VALUE_MEMORY_LIMIT
512M
```

### Cron
cron.yaml:
```
# Ref ./common-variables.yaml
x-mautic-volumes:
  &mautic-volumes
  - /mautic/config:/var/www/html/config:z
  - ../mautic/parameters_local.php:/var/www/html/config/parameters_local.php:z
  - /mautic/logs:/var/www/html/var/logs:z
  - /mautic/media/files:/var/www/html/docroot/media/files:z
  - /mautic/media/images:/var/www/html/docroot/media/images:z
  # - ../mautic/mautic_cron:/opt/mautic/cron/mautic:z

services:
  cron:
    build:
      context: .
      dockerfile: ../mautic/Dockerfile
    restart: unless-stopped
    links:
      - mariadb:mysql
    volumes: *mautic-volumes
    env_file:
      - ../.env
      - ../.mautic_env
    environment:
      - DOCKER_MAUTIC_ROLE=mautic_cron
      - MAUTIC_LOG_FILE_NAME=mautic-cron.log
    depends_on:
      web:
        condition: service_healthy
      mariadb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      rabbit-user-creator:
        condition: service_completed_successfully

networks:
  default:
    name: mautic
```

### Web
web.yaml
```
# Ref ./common-variables.yaml
x-mautic-volumes:
  &mautic-volumes
  - /mautic/config:/var/www/html/config:z
  - ../mautic/parameters_local.php:/var/www/html/config/parameters_local.php:z
  - /mautic/logs:/var/www/html/var/logs:z
  - /mautic/media/files:/var/www/html/docroot/media/files:z
  - /mautic/media/images:/var/www/html/docroot/media/images:z
  # - ../mautic/mautic_cron:/opt/mautic/cron/mautic:z

services:
  web:
    build:
      context: .
      dockerfile: ../mautic/Dockerfile
    restart: unless-stopped
    links:
      - mariadb:mysql
    volumes: *mautic-volumes
    ports:
      - 80:80
    env_file:
      - ../.env
      - ../.mautic_env
    environment:
      - DOCKER_MAUTIC_LOAD_TEST_DATA=${DOCKER_MAUTIC_LOAD_TEST_DATA}
      - DOCKER_MAUTIC_RUN_MIGRATIONS=${DOCKER_MAUTIC_RUN_MIGRATIONS}
      - MAUTIC_LOG_FILE_NAME=mautic-web.log
    healthcheck:
      test: curl localhost
      start_period: 5s
      interval: 10s
      timeout: 5s
      retries: 100
    depends_on:
      mariadb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      rabbit-user-creator:
        condition: service_completed_successfully


networks:
  default:
    name: mautic
```

### Worker
worker.yaml
```
# Ref ./common-variables.yaml
x-mautic-volumes:
  &mautic-volumes
  - /mautic/config:/var/www/html/config:z
  - ../mautic/parameters_local.php:/var/www/html/config/parameters_local.php:z
  - /mautic/logs:/var/www/html/var/logs:z
  - /mautic/media/files:/var/www/html/docroot/media/files:z
  - /mautic/media/images:/var/www/html/docroot/media/images:z
  # - ../mautic/mautic_cron:/opt/mautic/cron/mautic:z

services:
  worker:
    build:
      context: .
      dockerfile: ../mautic/Dockerfile
    restart: unless-stopped
    links:
      - mariadb:mysql
    volumes: *mautic-volumes
    env_file:
      - ../.env
      - ../.mautic_env
    environment:
      - DOCKER_MAUTIC_ROLE=mautic_worker
      - MAUTIC_LOG_FILE_NAME=mautic-worker.log
    depends_on:
      web:
        condition: service_healthy
      mariadb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      rabbit-user-creator:
        condition: service_completed_successfully

networks:
  default:
    name: mautic
```

Dockerfile:
```
FROM mautic/mautic:latest

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin --filename=composer

RUN apt-get update
RUN apt-get install --no-install-recommends -y \
  git \
  nodejs \
  npm \
  vim \
  htop

RUN cd /var/www/html && \
  COMPOSER_ALLOW_SUPERUSER=1 COMPOSER_PROCESS_TIMEOUT=10000 composer require pabloveintimilla/mautic-amazon-ses

RUN rm -rf /var/www/html/var/cache/js && \
  find /var/www/html/node_modules -mindepth 1 -maxdepth 1 -not \( -name 'jquery' -or -name 'vimeo-froogaloop2' \) | xargs rm -rf

# add the mautic env params to the cron
RUN sed -i '/declare -p | grep '\''PHP_INI_VALUE_'\'' > \/tmp\/cron.env/a env | grep MAUTIC | awk '\''{print "declare -x " $0}'\'' >> /tmp/cron.env' /entrypoint_mautic_cron.sh

# cleanup apt cache
RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
```

htop:

![Image](https://github.com/user-attachments/assets/12a07f11-1f08-4274-afe3-2799b2388624)

This looks like the `messenger:consume email` should not be in the crown as it is part of the worker suite:

```
root@mautic:~/mautic# docker compose exec -u www-data -w /var/www/html web php ./bin/console messenger:consume email

                                                                                                                        
 [OK] Consuming messages from transport "email".                                                                        
                                                                                                                        

 // The worker will automatically exit once it has received a stop signal via the messenger:stop-workers command.       

 // Quit the worker with CONTROL-C.                                                                                     

 // Re-run the command with a -vv option to see logs about consumed messages.
```
