### ISSUE TITLE
[Bug] mautic.core.update.archive_failed_to_extract

### ISSUE THREAD

**Issue by lordimac** [mautic/docker-mautic#399]
### Describe the bug

Hello, after updating mautic docker to version 5.2.5 I get the following error after trying to change the settings (for example changing the language).

mautic.core.update.archive_failed_to_extract

No other error shows up and the settings are not saved.

![Image](https://github.com/user-attachments/assets/b112490c-48bf-4ff0-8f4a-611ef04253ee)

Edit: Just found another related error in docker logs.

[Tue May 27 15:47:52.365629 2025] [php:warn] [pid 30:tid 30] [client 10.0.0.33:49766] PHP Warning:  ZipArchive::extractTo(): Permission denied in /var/www/html/docroot/app/bundles/CoreBundle/Helper/LanguageHelper.php on line 96, referer: https://newsletter.domain.tld/s/config/edit

### Steps to reproduce

Open Settings
Change Language
Save

### Expected behavior

Saving the settings

### Actual behavior

Not saving the settings

### Docker Image Tag

mautic/mautic:5-apache

### Server Architecture

AMD64 (Intel or AMD processors)

### Docker Image Digest (Optional but helpful)

sha256:016cdb835814986e94e89148ab5eaf682c4531392049d7232eef695e3f8b3eab

### Docker Compose (if applicable)

```
version: "3"
x-mautic-volumes: &a1
  - mautic-config:/var/www/html/config:z
  - mautic-logs:/var/www/html/var/logs:z
  - mautic-files:/var/www/html/docroot/media/files:z
  - mautic-images:/var/www/html/docroot/media/images:z
  - mautic-cron:/opt/mautic/cron:z
services:
  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: mysqladmin --user=$$MYSQL_USER --password=$$MYSQL_PASSWORD ping
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped
  mautic_web:
    image: mautic/mautic:5-apache
    links:
      - db:mysql
    ports:
      - 8001:80
    volumes: *a1
    environment:
      - DOCKER_MAUTIC_LOADs_TEST_DATA=${DOCKER_MAUTIC_LOAD_TEST_DATA}
      - DOCKER_MAUTIC_RUN_MIGRATIONS=${DOCKER_MAUTIC_RUN_MIGRATIONS}
    env_file:
      - .env
    healthcheck:
      test: curl http://localhost
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 100
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
  mautic_cron:
    image: mautic/mautic:5-apache
    links:
      - db:mysql
    volumes: *a1
    environment:
      - DOCKER_MAUTIC_ROLE=mautic_cron
    env_file:
      - .env
    depends_on:
      mautic_web:
        condition: service_healthy
    restart: unless-stopped
  mautic_worker:
    image: mautic/mautic:5-apache
    links:
      - db:mysql
    volumes: *a1
    environment:
      - DOCKER_MAUTIC_ROLE=mautic_worker
    env_file:
      - .env
    depends_on:
      mautic_web:
        condition: service_healthy
    restart: unless-stopped
volumes:
  mysql-data:
    driver: local
  mautic-config:
    driver: local
  mautic-logs:
    driver: local
  mautic-files:
    driver: local
  mautic-images:
    driver: local
  mautic-cron:
    driver: local
networks: {}
x-dockge:
  urls: []
```

### Acknowledgements

- [x] I agree to follow this project's [Code of Conduct](https://github.com/mautic/docker-mautic/blob/mautic5/CODE_OF_CONDUCT.md)
- [x] This issue is **NOT** a security vulnerability. (Security vulnerabilities should be reported via the [Security](https://github.com/mautic/docker-mautic/security) tab.)
