### ISSUE TITLE
[Bug]   `mautic:latest` cannot reach DB after upgrade from `mautic:v4-apache`

### ISSUE THREAD

**Issue by yossie-44** [mautic/docker-mautic#404]
### Describe the bug

After upgrading my container image from `mautic:v4-apache` to `mautic:latest`, Mautic can no longer connect to the MySQL container.  
The same `docker-compose.yml` worked flawlessly with `v4-apache`.

### Steps to reproduce

Change the image tag in docker-compose.yml

# Before
image: mautic/mautic:v4-apache

# After
image: mautic/mautic:latest

### Expected behavior

Mautic should start, migrate the database if needed, and be reachable on port 8080 just like with `v4-apache`.

### Actual behavior

Container exits (or keeps restarting) because it is unable to resolve/connect to the DB host.

### Docker Image Tag

 mautic/mautic:latest

### Server Architecture

AMD64 (Intel or AMD processors)

### Docker Compose (if applicable)

```
services:
  mautic:
    image: mautic/mautic:latest
    ports:
      - "8080:80"
    environment:
      MAUTIC_DB_HOST: mauticdb
      MAUTIC_DB_PORT: 3306
      MAUTIC_DB_USER: root
      MAUTIC_DB_PASSWORD: password
      MAUTIC_DB_NAME: mauticdb
    networks:
      - mauticnet

  mauticdb:
    image: mysql:latest
    environment:
      MYSQL_HOST: mauticdb
      MYSQL_PORT: 3306
      MYSQL_DATABASE: mauticdb
      MYSQL_USER: mautic
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    networks:
      - mauticnet

networks:
  mauticnet:
```

### Acknowledgements

- [x] I agree to follow this project's [Code of Conduct](https://github.com/mautic/docker-mautic/blob/mautic5/CODE_OF_CONDUCT.md)
- [x] This issue is **NOT** a security vulnerability. (Security vulnerabilities should be reported via the [Security](https://github.com/mautic/docker-mautic/security) tab.)
