### ISSUE TITLE
Problem linking the db

### ISSUE THREAD

**Issue by avifatal** [mautic/docker-mautic#48]
Hi,
I get this error when running the following yml file
`mautic_1    |  error: missing MAUTIC_DB_HOST and MYSQL_PORT_3306_TCP environment variables
mautic_1    |   Did you forget to --link some_mysql_container:mysql or set an external db
mautic_1    |   with -e MAUTIC_DB_HOST=hostname:port?
mautic_mautic_1 exited with code 1`

```
version : "3.5"

services:
 mautic:
  image: mautic/mautic
  links:
    - mauticdb:mysql
  ports:
    - 8182:80
  environment:
   - MAUTIC_DB_NAME="mautic"
   - MAUTIC_DB_USER="root"
   - MAUTIC_DB_PASSWORD="mautic"

 mauticdb:
  image: mysql:5.6
  environment:
   - MYSQL_ROOT_PASSWORD="mautic"

```

Any suggestions?
Thanks
