### ISSUE TITLE
-link option ignored in docker-compose

### ISSUE THREAD

**Issue by FabianTe** [mautic/docker-mautic#60]
Hi! In this docker-compose file, my `links` option is ignored.

```docker
version: '3'
services:
  mautic:
    image: mautic/mautic
    links:
      - db:mysql
    ports: 
      - 8080:80
    depends_on:
      - db

  db:
    image: mysql/mysql-server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
```

I get this log message:

```
mautic_1  | error: missing MAUTIC_DB_HOST and MYSQL_PORT_3306_TCP environment variables
mautic_1  |   Did you forget to --link some_mysql_container:mysql or set an external db
mautic_1  |   with -e MAUTIC_DB_HOST=hostname:port?
```

Do you get the same behaviour for the compose file?

Edit: I also get this with different mysql versions, including the latest and the version specified by the README

**Comment by salvacorts** [comment]
Hi @FabianTe, Docker links are a legacy feature that may be removed in the future as you can read in the note bellow.

> Warning: The --link flag is a legacy feature of Docker. It may eventually be removed. Unless you absolutely need to continue using it, we recommend that you use user-defined networks to facilitate communication between two containers instead of using --link. One feature that user-defined networks do not support that you can do with --link is sharing environmental variables between containers. However, you can use other mechanisms such as volumes to share environment variables between containers in a more controlled way.
[Legacy container links](https://docs.docker.com/network/links/)

In this case I would recommend you using docker networks.
You need to create a network for Mautic and MySQL and then set all the env variables needed to make them able to communicate between them.
Also, you can make all data from DB and Mautic persistent across reboots with volumes.

This is the content of my docker deployment configuration files:

_**docker-compose.yml**_
```yaml
version: '3.0'
services:
  mautic:
    image: mautic/mautic
    ports:
      - "80:80"
    env_file:
      - mautic.env
    volumes:
      - mautic-data:/var/www/html
    networks:
      - mautic-net
    depends_on:
      - db-mautic
  db-mautic:
    image: mysql:5.6
    volumes:
      - db-mautic-data:/var/lib/mysql
    env_file:
      - mautic.env
    networks:
      - mautic-net

volumes:
  db-mautic-data:
  mautic-data:

networks:
  mautic-net:
```
_**mautic.env**_
```bash
MYSQL_HOST=db-mautic
MYSQL_ROOT_PASSWORD=sierra75nevada
MYSQL_USER=mautic
MYSQL_PASSWORD=mautic
MYSQL_DATABASE=mautic

MAUTIC_DB_HOST=db-mautic:3306
MAUTIC_DB_USER=mautic
MAUTIC_DB_PASSWORD=mautic
MAUTIC_DB_NAME=mautic
```

If you wish, you can learn more about Docker networks here:

- [MySQL on Docker: Single Host Networking for MySQL Containers](https://severalnines.com/blog/mysql-docker-single-host-networking-mysql-containers)
- [Networking in Compose](https://docs.docker.com/compose/networking/)

Have a nice day!
